AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Naming/VariableName:
  EnforcedStyle: snake_case

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Lint/Syntax:
  Enabled: false
