# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: mysecretpassword
  host: localhost
  port: 5432

development:
  <<: *default
  database: sns_server

production:
  <<: *default
  database: sns_server